### ISSUE TITLE
Links to headings do not contain global base path

### ISSUE THREAD

**Issue by r0bb3n** [pauloue/mkdocs-autoreflinks-plugin#3]
Hi,

first of all, thanks for that plugin! Unfortunately I have an issue when publishing the outcome, maybe I missed a special setting. 🤔

My final documentation will be hosted on a sub path of a domain, e.g. `https://my.doma.in/wiki` and therefore the MkDocs property `site_url` is set accordingly. When running locally with `mkdocs serve` it works fine, because it ignores that setting and uses `http://127.0.0.1:8000/` without base path and the links your plugin generates are functional. But when I build the HTML files (`mkdocs build`), the generated links by the plugin still start with `/` followed by either the anchor directly or the page path + anchor and do not work. How can I tell your plugin to use a base path (e.g. `/wiki`) in this links? 

I put a [sample project on gist](https://gist.github.com/r0bb3n/fc3e2dbab49f547854eced6f9e456f1a) with: 
* docs/index.md
* mkdocs.yml
* site/index.html (snippet)

Thanks in advance.

Kind regards,
r0bb3n

**Comment by p-ouellette** [comment]
That should fix it: https://github.com/pauloue/mkdocs-autoreflinks-plugin/commit/6206c54f2aa3a44381c25141988d354e5fa79707

**Comment by r0bb3n** [comment]
Wow, that was quick and yes, it works.

Thank you very much!!!
